# Midterm 3

#### Instructions:
- Please read these instructions as well as the questions carefully.
- Your best resource is likely the official documentation of the datascience package: http://data8.org/datascience.
- Feel free to use Excel to play with the data.
- Please complete this notebook by filling in the cells provided. Before you begin, execute the following cell. Each time you start Jupyter Notebook, you will need to execute this cell.
- Please be sure not to re-assign variables throughout the notebook. For example, if you use `max_price` in your answer to one question, do not re-assign it later on.
- Please be sure not to re-define functions throughout the notebook. For example, if a question asks you to define `sharpe_ratio()`, the notebook that you submit should contain only one definition of that function.

In [1]:
# don't change this cell; just run it
from datascience import *
import numpy as np

Let's start by loading some data. Just as a stock index fund can be used as a benchmark for an active stock fund, a bond index fund (VBMFX) can be used as a benchmark for an active municipal (tax-exempt) bond fund (VMATX), after some adjustments.

In [2]:
muni = Table.read_table('https://www.dropbox.com/s/36pkujkvtxm5yji/vanguard_muni.csv?raw=1')
muni

Date   | VBMFX | VMATX   | RF
199901 | 0.79  | 1.249   | 0.35
199902 | -1.77 | -0.5799 | 0.35
199903 | 0.56  | -0.1431 | 0.43
199904 | 0.4   | 0.3532  | 0.37
199905 | -0.88 | -0.9548 | 0.34
199906 | -0.5  | -1.7755 | 0.4
199907 | -0.39 | 0.3866  | 0.38
199908 | -0.08 | -1.2743 | 0.39
199909 | 1.26  | -0.4563 | 0.39
199910 | 0.33  | -1.5447 | 0.39
... (244 rows omitted)

#### Question 1
Find the number of rows in `muni`.

In [4]:
n = muni.num_rows
n

254

Calculate the 10th percentile of VBMFX's returns.

In [5]:
VBMFX_p10 = np.percentile(muni.column('VBMFX'), 10)
VBMFX_p10

-0.787

Calculate the *corr*elation *coef*ficient of VBMFX and VMATX. If the function you use returns the correlation matrix, you need to extract from it the number between -1 and 1. It is acceptable to just copy-and-paste.

In [8]:
corrcoef = np.corrcoef(muni.column('VMATX'), muni.column('VBMFX'))
corrcoef

array([[1.      , 0.689348],
       [0.689348, 1.      ]])

#### Question 2
Create the array `VBMFX_crashes` that contains the 10 worst monthly returns for VBMFX, from the worst to the 10th worst.

In [ ]:
VBMFX_crashes = muni.column('VBMFX').sort(descen)
VBMFX_crashes

#### Question 3
VMATX's returns in `muni` are after-tax returns for Massachusetts residents. On the other hand, VBMFX's returns are before tax. Suppose one's tax rate is 30%, so that 1% in after-tax return is equivalent to 1/(1-.3)=1/.7=1.43% before tax. Create the array `before_tax` that contains the before-tax returns of VMATX.

In [ ]:
before_tax = ...
before_tax

#### Question 4
Create the Table `muni2` that contains before-tax, excess returns for both VBMFX and VMATX. Keep VBMFX and VMATX as column labels. Use this Table instead of `muni` henceforth.

In [ ]:
muni2 = ...
muni2

#### Question 5
Calculate the mean and SD of excess returns for VBMFX.

In [6]:
VBMFX_mean = np.mean(muni.column('VBMFX')-muni.column('RF'))
VBMFX_sd = np.std(muni.column('VBMFX')-muni.column('RF'))
make_array(VBMFX_mean, VBMFX_sd)

array([0.23956693, 0.99129052])

#### Question 6
Calculate the mean and SD of excess returns for VMATX.

In [7]:
VMATX_mean = np.mean(muni.column('VMATX')-muni.column('RF'))
VMATX_sd = np.mean(muni.column('VMATX')-muni.column('RF'))
make_array(VMATX_mean, VMATX_sd)

array([0.24005669, 0.24005669])

#### Question 7
Calculate the Sharpe ratios of the funds.

In [ ]:
VBMFX_sr = ...
VMATX_sr = ...
make_array(VBMFX_sr, VMATX_sr)

#### Question 8
For a taxable Massachusetts investor, VMATX can be think of as a levered version of VBMFX: very roughly VMATX has twice the mean and SD as VBMFX. The main analysis of **Why *Not* 100% Equities** assumes that the levered 60/40 portfolio can borrow at the T-bill rate. In the endnotes, the author finds that assuming the borrow rate to be T-bill + $x$ basis points causes the levered 60/40 portfolio to have a 10.81% compound return. What's $x$?

In [ ]:
x = ...

Research the interest charged on margin loans by InteractiveBrokers, a broker known for very competitive pricing. Their "Benchmark Rate" is roughly the T-bill rate. Is Asness' relatively conservative assumption (T-bill + $x$ basis points) in the endnotes realistic for someone whose portfolio is less than $1 million? Assign `True` or `False` to `realistic` below. Recall that `True` and `False` are boolean values (no quotes).

In [ ]:
realistic = ...

#### Question 9
The following code cell loads the 6 Fama-French portfolios formed on size and book-to-market. Calculate the array `SMB` that contains the SMB (Small Minus Big) factor according to the description at http://mba.tuck.dartmouth.edu/pages/faculty/ken.french/Data_Library/f-f_factors.html.

In [ ]:
two_by_three = Table.read_table('https://www.dropbox.com/s/ic0ofx6gibwl22k/6_Portfolios_2x3.CSV?raw=1')
two_by_three

In [ ]:
SMB = ...
SMB

#### Question 10
The following code cell loads 2 Vanguard index funds. Find the minimum-risk mix of equities (VFINX) and bonds (VBMFX). In other words, approximate the value for w_e, the weight for equities, that gives the lowest SD among portfolios that invest in the two funds.

In [ ]:
vanguard = Table.read_table('https://www.dropbox.com/s/dsvvbmnc5rxxl3u/vanguard_stock_bond.csv?raw=1')
vanguard

In [ ]:
w_e_min = ...
w_e_min

## Submission

Once you're finished, select "Save and Checkpoint" in the File menu. Pay attention to the name of your notebook---it's to the right of the "jupyter" logo at the upper left-hand corner of the page. On your computer your notebook has a file extension .ipynb. Locate and submit it on Gradescope.