# Homework 3

#### Instructions:
- Please read these instructions as well as the questions carefully.
- Your best resource is likely the official documentation of the datascience package: http://data8.org/datascience.
- Feel free to use Excel to play with the data.
- Please complete this notebook by filling in the cells provided. Before you begin, execute the following cell. Each time you start Jupyter Notebook, you will need to execute this cell.
- Please be sure not to re-assign variables throughout the notebook. For example, if you use `max_price` in your answer to one question, do not re-assign it later on.
- Please be sure not to re-define functions throughout the notebook. For example, if a question asks you to define `sharpe_ratio()`, the notebook that you submit should contain only one definition of that function.

In [36]:
# Don't change this cell; just run it.
from datascience import *
import numpy as np

## A. Creating Arrays

#### Question 1
Make an array called `weird_numbers` containing the following numbers (in the given order):

1. -2
2. the sine of 1.2
3. 3
4. 5 to the power of the cosine of 1.2

*Hint:* `sin` and `cos` are functions in the `math` module.

In [24]:
import math

weird_numbers = [-2, math.sin(1.2),3,5**math.cos(1.2)]
weird_numbers

[-2, 0.9320390859672263, 3, 1.7917491256752254]

## B. Indexing Arrays
These exercises give you practice accessing individual elements of arrays. In Python (and in many programming languages), elements are accessed by *index* and the first element is the element at index 0.

#### Question 1
The cell below creates an array of some numbers. Set `third_element` to the third element of `some_numbers`.

In [25]:
some_numbers = make_array(-1, -3, -6, -10, -15)

third_element = some_numbers[2]
third_element

-6

#### Question 2
The next cell creates a Table that displays some information about the elements of `some_numbers` and their order. Run the cell to see the partially-completed table, then fill in the missing information in the cell (the strings that are currently "???") to complete the table.

In [26]:
elements_of_some_numbers = Table().with_columns(
    "English name for position", make_array("first", "second", "third", "fourth", "fifth"),
    "Index",                     make_array(0, 1, 2, 3, 4),
    "Element",                   some_numbers)
elements_of_some_numbers

English name for position | Index | Element
first                     | 0     | -1
second                    | 1     | -3
third                     | 2     | -6
fourth                    | 3     | -10
fifth                     | 4     | -15

#### Question 3
You'll sometimes want to find the *last* element of an array. Suppose an array has 142 elements. What is the index of its last element?

In [59]:
index_of_last_element = len(np.arange(142))-1

More often, you don't know the number of elements in an array, its *length*. For example, it might be a large dataset you found on the Internet. The function `len()` takes a single argument, an array, and returns the `len`gth of that array (an integer).

#### Question 4
The cell below loads an array called `msft_closing_prices`. The last element in that array is the most recent closing price of Microsoft in the sample. Assign that price to `most_recent_closing_price`.

In [56]:
msft_closing_prices = Table.read_table("https://www.dropbox.com/s/46ypdrs5bicrr16/msft.csv?raw=1").column('PRC')

most_recent_closing_price = msft_closing_prices[-1]
most_recent_closing_price

101.57

## C. Basic Array Arithmetic

#### Question 1
Multiply the numbers 42, 4224, 42422424, and -250 by 157. For this question, **don't** use arrays.

In [15]:
first_product = 42 * 157
second_product = 4224*157
third_product = 42422424*157
fourth_product = -250*157
print(first_product, second_product, third_product, fourth_product)

6594 663168 6660320568 -39250


#### Question 2
Now, do the same calculation, but using an array called `numbers` and only a single multiplication (`*`) operator. Store the 4 results in an array named `products`.

In [76]:
numbers = make_array(42,4224,42422424,-250)
products = numbers*157
products

array([      6594,     663168, 6660320568,     -39250])

#### Question 3
Oops, we made a typo! Instead of 157, we wanted to multiply each number by 1577. Compute the fixed products in the cell below using array arithmetic. Notice that your job is really easy if you previously defined an array containing the 4 numbers.

In [78]:
fixed_products = numbers*1577
fixed_products

array([      66234,     6661248, 66900162648,     -394250])

#### Question 4
We've loaded an array of (Microsoft) closing prices and an array of shares outstanding in the next cell. Compute the market capitalization for each month. That is, compute the product between each monthly closing price and the corresponding monthly shares outstanding.

In [19]:
msft = Table.read_table("https://www.dropbox.com/s/46ypdrs5bicrr16/msft.csv?raw=1")
msft_closing_prices = msft.column('PRC')
msft_shares_outstanding = msft.column('SHROUT')

market_capitalizations = (msft_closing_prices*msft_shares_outstanding)
market_capitalizations

array([3.02190810e+08, 2.75849485e+08, 2.66771640e+08, 2.86430232e+08,
       2.93606294e+08, 2.76428600e+08, 2.71926200e+08, 2.69357885e+08,
       2.75598300e+08, 3.44373710e+08, 3.14342750e+08, 3.32112400e+08,
       3.03407548e+08, 2.53148925e+08, 2.64217800e+08, 2.65615116e+08,
       2.63752458e+08, 2.51744010e+08, 2.34831136e+08, 2.49165696e+08,
       2.39596130e+08, 1.98638145e+08, 1.79868486e+08, 1.72802160e+08,
       1.52028627e+08, 1.43582592e+08, 1.63456260e+08, 1.80308327e+08,
       1.85915151e+08, 2.11743160e+08, 2.09579052e+08, 2.19648114e+08,
       2.28908000e+08, 2.46218025e+08, 2.61134949e+08, 2.68559280e+08,
       2.47151591e+08, 2.51449117e+08, 2.56617075e+08, 2.67603824e+08,
       2.26107046e+08, 1.99118577e+08, 2.23348564e+08, 2.03055950e+08,
       2.09683380e+08, 2.28133021e+08, 2.16091122e+08, 2.34527730e+08,
       2.32956041e+08, 2.23335314e+08, 2.14063090e+08, 2.18577321e+08,
       2.10903503e+08, 2.17776000e+08, 2.29564488e+08, 2.22861876e+08,
      

## D. Tables

#### Question 1
Suppose you have 4 apples, 3 oranges, and 3 pineapples. Create a Table that contains this information. It should have two columns: "fruit name" and "count". Give it the name `fruits`. The name of each fruit should be lower-case and singular, like "strawberry".

In [82]:
# Our solution uses 1 statement split over 3 lines.
fruits = Table().with_columns("fruit name", make_array("apple", "orange", "pineapple"),
                            "count", make_array(4,3,3))
fruits

fruit name | count
apple      | 4
orange     | 3
pineapple  | 3

## Submission
Once you're finished, select "Save and Checkpoint" in the File menu. Pay attention to the name of your notebook---it's to the right of the "jupyter" logo at the upper left-hand corner of the page. On your computer your notebook has a file extension .ipynb. Locate and submit it on Gradescope.