# Homework 9

#### Instructions:
- Please read these instructions as well as the questions carefully.
- Your best resource is likely the official documentation of the datascience package: http://data8.org/datascience.
- Feel free to use Excel to play with the data.
- Please complete this notebook by filling in the cells provided. Before you begin, execute the following cell. Each time you start Jupyter Notebook, you will need to execute this cell.
- Please be sure not to re-assign variables throughout the notebook. For example, if you use `max_price` in your answer to one question, do not re-assign it later on.
- Please be sure not to re-define functions throughout the notebook. For example, if a question asks you to define `sharpe_ratio()`, the notebook that you submit should contain only one definition of that function.

In [4]:
# don't change this cell; just run it
from datascience import *
import numpy as np

Let's start by loading the data, which are monthly (percentage) returns for three assets.

In [6]:
vanguard = Table.read_table('https://www.dropbox.com/s/dsvvbmnc5rxxl3u/vanguard_stock_bond.csv?raw=1')
vanguard.show()

#### Question 1
RF is the risk-free asset. VFINX and VBMFX are tickers for two Vanguard index mutual funds. Which one is the equity index fund and which one the bond index fund?

In [ ]:
equity_ticker = 'VFINX' 
bond_ticker = 'VBMFX'

In [71]:
sort2 = vanguard.sort('VBMFX',descending = False).show()

In [72]:
sort1 = vanguard.sort('VFINX',descending = False).show()

In [64]:
sixty =  np.percentile(vanguard.column('VFINX'),60)
sixty

2.0519999999999996

In [65]:
fourty = np.percentile(vanguard.column('VBMFX'),40)
fourty

0.2180000000000001

#### Question 2
Compute the array `sixty_forty` that contains the returns to a monthly-rebalanced 60/40 portfolio.

In [49]:
sixty1 =  np.arrvanguard.column('VFINX')
fourty1 = vanguard.column('VBMFX')
sixty_forty = sixty1 + fourty1
sixty_forty


AttributeError: 'numpy.ndarray' object has no attribute 'index'

Create the Table `vanguard2` that adds to the data in the Table `vanguard` with a new column. That new column should have the label `sixty_forty` and contain the array you just created.

In [21]:
vanguard2 = vanguard.with_column('sixty_forty', sixty_forty)
vanguard2.show()

#### Question 3
Calculate the mean and SD of returns for VFINX.

In [3]:
VFINX_mean = np.mean(vanguard.column('VFINX'))
VFINX_sd = np.std(vanguard.column('VFINX'))
make_array(VFINX_mean, VFINX_sd)

array([0.89964824, 4.26756505])

#### Question 4
Calculate the mean and SD of returns for VBMFX.

In [4]:
VBMFX_mean = np.mean(vanguard.column('VBMFX'))
VBMFX_sd = np.std(vanguard.column('VBMFX'))
make_array(VBMFX_mean, VBMFX_sd)

array([0.48824121, 1.09847515])

#### Question 5
Calculate the mean and SD of returns for `sixty_forty`.

In [45]:
sixty_forty_mean = np.mean(vanguard2.column('sixty_forty'))
sixty_forty_sd = np.std(vanguard2.column('sixty_forty'))
make_array(sixty_forty_mean, sixty_forty_sd)

array([1.38788945, 4.47983613])

#### Question 6
Calculate the leverage ratio, the equivalent of 1.55 in the paper. This is discussed in a paragraph below Exhibit 4.

In [1]:
ratio = 1+0.55*1
ratio

1.55

In the paper, the leverage ratio is 1.55. That means that for $1 investment, the levered 60/40 portfolio holds \"1.55 dollars of the 60/40 portfolio, and financing this with 55 cents of borrowing\" at the risk-free rate. Let's say on a given month:

- we start with $1
- the return of the 60/40 portfolio is 1\%
- the risk-free rate is 0.1\%.

Our revenue over the month is 1.55 cents. Our cost for borrowing 55 cents is 0.055 cents. What is the profit (revenue minus cost) in cents?

In [2]:
profit = 1.55-0.055
profit

1.495

#### Question 7
Compute the array `levered` that contains the returns to the levered 60/40 portfolio.  Make sure that the costs of borrowing are accounted for.

In [23]:
levered = ratio * vanguard2.column('sixty_forty')

levered

array([ 2.25680e+01,  6.99050e+00,  3.42550e+00, -6.49450e+00,
        1.00750e+00,  9.98200e+00,  7.44000e+00,  4.75850e+00,
       -7.03700e+00, -2.82565e+01, -1.16250e+01,  1.42135e+01,
        1.12530e+01,  8.95900e+00, -6.49450e+00,  6.97500e-01,
       -2.32500e-01,  1.12220e+01, -1.31750e+00, -4.99100e+00,
        9.99750e+00,  6.49450e+00, -3.50300e+00,  3.27050e+00,
        1.26945e+01, -4.78950e+00,  3.90600e+00,  1.10980e+01,
        1.01990e+01,  3.62700e+00,  1.73600e+01,  4.03000e-01,
        1.24000e-01,  1.86000e-01,  4.32450e+00,  4.83600e+00,
       -1.33455e+01,  3.13100e+00,  4.16950e+00, -5.27000e+00,
        1.94525e+01,  1.41050e+00,  1.47250e+00, -1.58720e+01,
       -6.46350e+00,  1.67400e+00,  1.34385e+01,  6.46350e+00,
        8.43200e+00,  1.22915e+01,  4.80500e+00,  1.84450e+00,
        7.67250e+00, -7.16100e+00,  9.22250e+00,  6.78900e+00,
        5.27000e-01,  3.54950e+00, -5.06850e+00,  2.23975e+01,
       -5.06850e+00,  2.88300e+00, -3.76650e+00,  5.611

Create the Table `vanguard3` that adds to the data in Table `vanguard2` with a new column. That new column should have label `levered` and data the array you just created.

In [24]:
vanguard3 = vanguard2.with_column('levered', levered)
vanguard3.show()

#### Question 8
Calculate the mean and SD of returns for `levered`.

In [40]:
levered_mean = np.mean(vanguard3.column('levered'))
levered_sd = np.std(vanguard3.column('levered'))
make_array(levered_mean, levered_sd)

array([2.15122864, 6.943746  ])

#### Question 9
Find the worst month, in the form of a 6-digit monthly date, and the return over that month for `VFINX`.

In [42]:
min = np.min(vanguard3.column('VFINX'))
min

-21.73

In [44]:
VFINX_worst_month = 198710
VFINX_worst_monthly_return = np.min(vanguard3.column('VFINX'))

#### Question 10
Find the worst month and the return over that month for `levered`.

In [ ]:
levered_worst_month = ...
levered_worst_monthly_return = np.min(vanguard3.column('levered'))