# Homework 9

#### Instructions:
- Please read these instructions as well as the questions carefully.
- Your best resource is likely the official documentation of the datascience package: http://data8.org/datascience.
- Feel free to use Excel to play with the data.
- Please complete this notebook by filling in the cells provided. Before you begin, execute the following cell. Each time you start Jupyter Notebook, you will need to execute this cell.
- Please be sure not to re-assign variables throughout the notebook. For example, if you use `max_price` in your answer to one question, do not re-assign it later on.
- Please be sure not to re-define functions throughout the notebook. For example, if a question asks you to define `sharpe_ratio()`, the notebook that you submit should contain only one definition of that function.

In [1]:
# don't change this cell; just run it
from datascience import *
import numpy as np

Let's start by loading the data, which are monthly (percentage) returns for three assets.

In [2]:
vanguard = Table.read_table('https://www.dropbox.com/s/dsvvbmnc5rxxl3u/vanguard_stock_bond.csv?raw=1')
vanguard.show()

#### Question 1
RF is the risk-free asset. VFINX and VBMFX are tickers for two Vanguard index mutual funds. Which one is the equity index fund and which one the bond index fund?

In [3]:
equity_ticker = 'VFINX'
bond_ticker = 'VBMFX'

#### Question 2
Compute the array `sixty_forty` that contains the returns to a monthly-rebalanced 60/40 portfolio.

In [4]:
sixty_forty = .6 * vanguard.column('VFINX') + .4 * vanguard.column('VBMFX')
sixty_forty

array([ 8.4780e+00,  2.5980e+00,  1.4560e+00, -1.8740e+00,  4.6800e-01,
        3.5800e+00,  2.9020e+00,  1.9960e+00, -2.2740e+00, -1.1638e+01,
       -4.6380e+00,  5.1780e+00,  3.7380e+00,  3.2300e+00, -2.2840e+00,
        3.8200e-01,  1.0200e-01,  3.8080e+00, -4.1400e-01, -1.9680e+00,
        3.4320e+00,  2.2220e+00, -1.1840e+00,  1.1760e+00,  4.7400e+00,
       -1.7300e+00,  1.4600e+00,  3.9000e+00,  3.4400e+00,  8.1800e-01,
        6.2820e+00,  4.7600e-01, -4.8000e-02, -4.2000e-01,  1.5240e+00,
        1.7240e+00, -4.7880e+00,  1.0620e+00,  1.5980e+00, -1.8600e+00,
        6.9580e+00,  2.2600e-01,  3.1600e-01, -5.9020e+00, -2.6460e+00,
        3.5000e-01,  4.7560e+00,  2.2120e+00,  3.0400e+00,  4.6020e+00,
        1.7220e+00,  5.1600e-01,  2.8340e+00, -2.7600e+00,  3.3060e+00,
        2.2180e+00, -1.9800e-01,  1.1820e+00, -2.1100e+00,  8.0620e+00,
       -1.6840e+00,  9.9200e-01, -1.3580e+00,  2.0300e+00,  1.0240e+00,
       -3.7000e-01,  3.1880e+00, -8.5000e-01,  1.2060e+00, -2.90

Create the Table `vanguard2` that adds to the data in the Table `vanguard` with a new column. That new column should have the label `sixty_forty` and contain the array you just created.

In [5]:
vanguard2 = vanguard.with_column('sixty_forty', sixty_forty)
vanguard2.show()

#### Question 3
Calculate the mean and SD of returns for VFINX.

In [6]:
VFINX_mean = np.mean(vanguard2.column('VFINX'))
VFINX_sd = np.std(vanguard2.column('VFINX'))
make_array(VFINX_mean, VFINX_sd)

array([0.89964824, 4.26756505])

#### Question 4
Calculate the mean and SD of returns for VBMFX.

In [7]:
VBMFX_mean = np.mean(vanguard2.column('VBMFX'))
VBMFX_sd = np.std(vanguard2.column('VBMFX'))
make_array(VBMFX_mean, VBMFX_sd)

array([0.48824121, 1.09847515])

#### Question 5
Calculate the mean and SD of returns for `sixty_forty`.

In [8]:
sixty_forty_mean = np.mean(vanguard2.column('sixty_forty'))
sixty_forty_sd = np.std(vanguard2.column('sixty_forty'))
make_array(sixty_forty_mean, sixty_forty_sd)

array([0.73508543, 2.62782518])

#### Question 6
Calculate the leverage ratio, the equivalent of 1.55 in the paper. This is discussed in a paragraph below Exhibit 4.

In [9]:
ratio = 4.26756505 / 2.62782518
ratio

1.623991231410607

In the paper, the leverage ratio is 1.55. That means that for $1 investment, the levered 60/40 portfolio holds \"1.55 dollars of the 60/40 portfolio, and financing this with 55 cents of borrowing\" at the risk-free rate. Let's say on a given month:

- we start with $1
- the return of the 60/40 portfolio is 1\%
- the risk-free rate is 0.1\%.

Our revenue over the month is 1.55 cents. Our cost for borrowing 55 cents is 0.055 cents. What is the profit (revenue minus cost) in cents?

In [10]:
profit = 1.55 - .055
profit

1.495

#### Question 7
Compute the array `levered` that contains the returns to the levered 60/40 portfolio.  Make sure that the costs of borrowing are accounted for.

In [11]:
levered = vanguard2.column('sixty_forty') + (ratio-1)*(vanguard2.column('sixty_forty')-vanguard2.column('RF'))
levered

array([ 1.35061213e+01,  3.95081299e+00,  2.07125535e+00, -3.31791571e+00,
        5.22911228e-01,  5.51437282e+00,  4.42578659e+00,  2.94821062e+00,
       -3.97375211e+00, -1.92744047e+01, -7.75046826e+00,  8.16567002e+00,
        5.88952177e+00,  4.95845571e+00, -3.98375211e+00,  3.33328684e-01,
       -1.52588422e-01,  5.87840291e+00, -9.90567898e-01, -3.56416957e+00,
        5.18666334e+00,  3.22787387e+00, -2.27848062e+00,  1.51669921e+00,
        7.35452326e+00, -3.19013948e+00,  1.95295307e+00,  5.91549168e+00,
        5.09357676e+00,  8.85391053e-01,  9.76511905e+00,  3.11266315e-01,
       -4.83545880e-01, -1.10639035e+00,  2.04440869e+00,  2.41912623e+00,
       -8.13134502e+00,  1.36900369e+00,  2.19578360e+00, -3.45117764e+00,
        1.08754170e+01, -2.60924575e-02,  8.88671918e-02, -9.99663046e+00,
       -4.67147554e+00,  1.44082894e-01,  7.36802729e+00,  3.21787387e+00,
        4.61245790e+00,  7.17409186e+00,  2.52195676e+00,  5.07264123e-01,
        4.30911527e+00, -

Create the Table `vanguard3` that adds to the data in Table `vanguard2` with a new column. That new column should have label `levered` and data the array you just created.

In [12]:
vanguard3 = vanguard2.with_column('levered', levered)
vanguard3.show()

#### Question 8
Calculate the mean and SD of returns for `levered`.

In [13]:
levered_mean = np.mean(vanguard3.column('levered'))
levered_sd = np.std(vanguard3.column('levered'))
make_array(levered_mean, levered_sd)

array([1.03645751, 4.26242017])

#### Question 9
Find the worst month, in the form of a 6-digit monthly date, and the return over that month for `VFINX`.

In [14]:
def worst_month(table, label):
    return table.select('Date', label).sort(label).take(0)
    
worst_month(vanguard3, 'VFINX')

Date   | VFINX
198710 | -21.73

In [15]:
VFINX_worst_month = 198710
VFINX_worst_monthly_return = -21.73

#### Question 10
Find the worst month and the return over that month for `levered`.

In [16]:
worst_month(vanguard3, 'levered')

Date   | levered
198710 | -19.2744

In [17]:
levered_worst_month = 198710
levered_worst_monthly_return = -19.2744