In [3]:
from datascience import *
import numpy as np

%matplotlib inline
import matplotlib.pyplot as plots
plots.style.use('fivethirtyeight')

## Apply with Multiple Columns

In [6]:
the_four = Table.read_table('https://www.dropbox.com/s/fbfrt3ot9k3vrqc/the_four.csv?raw=1')
the_four.show()

In [7]:
def multiply(x, y):
    return x * y

the_four.apply(multiply, 'prc', 'rtn')

array([  4.82426075,   1.64207025,   1.84975613, ...,  63.49957432,
        35.69877849, -92.72500381])

### Why are some prices negative?
In this dataset, a negative price means that an end-of-day transaction price is not available, so the average of the last best bid/ask prices is computed and included (with a negative sign).
<br>We need to replace prc with abs(prc).

In [8]:
the_four = the_four.select('date', 'year', 'ticker', 'rtn').with_column('prc', abs(the_four.column('prc')))
the_four.show()

## Function with Optional Arguments

In [10]:
def percents(s, places):
    return np.round(s / sum(s) * 100, places)

In [11]:
x = make_array(2, 5, 16)
percents(x, 4)

array([ 8.6957, 21.7391, 69.5652])

In [12]:
def percents(s, places=2):
    return np.round(s / sum(s) * 100, places)

In [13]:
percents(x)

array([ 8.7 , 21.74, 69.57])

## Grouping by Category

In [14]:
the_four.group('year').show()

In [15]:
the_four.where('ticker', 'AAPL').show()

In [16]:
the_four.select('ticker', 'rtn').group('ticker', np.std)

ticker | rtn std
AAPL   | 0.132141
AMZN   | 0.178704
GOOG   | 0.0915566
MSFT   | 0.0987773

In [18]:
the_four.where('ticker', 'AMZN').sort('rtn').show()

In [17]:
the_four.group('ticker', np.mean)

ticker | date mean | year mean | rtn mean  | prc mean
AAPL   | 199956    | 1999.5    | 0.0216385 | 103.643
AMZN   | 200777    | 2007.7    | 0.0407226 | 266.741
GOOG   | 201138    | 2011.31   | 0.0220305 | 625.618
MSFT   | 200219    | 2002.12   | 0.0236557 | 60.8073

In [27]:
min(the_four.where('ticker', 'AMZN').column('prc'))

5.97

In [25]:
def spread(arr):
    return max(arr) - min(arr)

spread(make_array(7, 10, 2))

8

In [26]:
the_four.group('ticker', spread)

ticker | date spread | year spread | rtn spread | prc spread
AAPL   | 3711        | 37          | 1.03122    | 654.292
AMZN   | 2106        | 21          | 1.67538    | 2006.74
GOOG   | 1403        | 14          | 0.655761   | 1088.59
MSFT   | 3208        | 32          | 0.859073   | 158.85

## More Examples

In [28]:
# historically, the amount of money it takes to buy one share of each of the stocks
the_four.select('date', 'prc').group('date', sum).show()

In [21]:
# average monthly return for each stock
the_four.select('ticker', 'rtn').group('ticker', np.average)

ticker | rtn average
AAPL   | 0.0216385
AMZN   | 0.0407226
GOOG   | 0.0220305
MSFT   | 0.0236557

In [22]:
# average monthly return for each stock-year
the_four.select('ticker', 'year', 'rtn').group(['ticker', 'year'], np.average).show()

/Users/hapham/opt/anaconda3/lib/python3.9/site-packages/datascience/tables.py:920: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  values = np.array(tuple(values))


## Pivot Tables

In [29]:
the_four.group(['ticker', 'year'])

ticker | year | count
AAPL   | 1981 | 12
AAPL   | 1982 | 12
AAPL   | 1983 | 12
AAPL   | 1984 | 12
AAPL   | 1985 | 12
AAPL   | 1986 | 12
AAPL   | 1987 | 12
AAPL   | 1988 | 12
AAPL   | 1989 | 12
AAPL   | 1990 | 12
... (98 rows omitted)

In [30]:
the_four.pivot('ticker', 'year', values='rtn', collect=np.average).show()

In [31]:
the_four.pivot('ticker', 'year').show()