In [6]:
from datascience import *
import numpy as np

## Review ##

In [7]:
mega_growth = Table.read_table('https://www.dropbox.com/s/kaw56kq3iyyicvf/mega_growth.csv?raw=1')
mega_growth

Firm      | Ticker | Price   | PE
Alphabet  | GOOG   | 1601.07 | 35
Amazon    | AMZN   | 3313.74 | 127
Apple     | AAPL   | 493.91  | 37
Microsoft | MSFT   | 215.69  | 37

In [8]:
x = mega_growth

In [ ]:
y = x.drop('Price')
y

In [ ]:
x = mega_growth.select('Firm', 'Price')
x

In [ ]:
y

## Numbers ##

In [ ]:
10 * 3

In [ ]:
10       # int 

In [ ]:
11.5 / 3 # float

In [ ]:
10 / 2   # still a float

In [ ]:
123 ** 4

In [ ]:
1234567 ** 890

In [ ]:
.12345678901234567890123456789

In [ ]:
30 / 400

In [ ]:
30 / 4000000000

In [ ]:
9 ** 0.5

In [ ]:
13 ** 0.5

In [ ]:
(13 ** 0.5) ** 2

In [ ]:
float(3)

In [ ]:
round(6.75)

## Strings ##

In [ ]:
'this is a string'

In [ ]:
'any snippet of text'

In [ ]:
'2' + 'x'    # concatenation

In [1]:
'straw' + 'berry'

'strawberry'

In [ ]:
'two ' + 'words'

In [ ]:
'ha' * 5

In [ ]:
str(2)

In [ ]:
int('123')

In [ ]:
int('2.3')

In [2]:
float('2.3')

2.3

In [ ]:
str('3')

In [ ]:
'2' + 'x'

In [ ]:
"I'm a data scientist!"

## Types ##

In [9]:
x = 2.3
type(x)

float

In [10]:
type(100)

int

In [11]:
type('abcd')

str

In [12]:
a = 5.7
type(a)

float

In [13]:
type(mega_growth)

datascience.tables.Table

## Arrays ##

In [14]:
make_array(1, '2.', 3, 4)

array(['1', '2.', '3', '4'], dtype='<U21')

In [15]:
my_array = make_array(5, 6, 7, 8)

In [16]:
my_array

array([5, 6, 7, 8])

In [17]:
len(my_array)

4

In [18]:
sum(my_array)

26

In [19]:
sum(my_array) / len(my_array)

6.5

In [ ]:
my_array

In [20]:
my_array * 2

array([10, 12, 14, 16])

In [21]:
another_one = make_array(20, 30, 40, 50)

In [22]:
my_array + another_one

array([25, 36, 47, 58])

In [23]:
yet_another = make_array(1, 2, 3, 4, 5, 6)
my_array + yet_another

ValueError: operands could not be broadcast together with shapes (4,) (6,) 

In [24]:
my_array

array([5, 6, 7, 8])

In [ ]:
my_array.item(0)

## Columns of Tables are Arrays ##

In [ ]:
mega_growth.select('Price')

In [ ]:
mega_growth.column('Price')